Repository wiremock/wiremock-docker, pull requests merged in 2023-10, with the labels that each got.

#88 Add integration test for the webhooks extension
  test/integration-tests/src/test/java/org/wiremock/docker/it/TestConfig.java
  test/integration-tests/src/test/java/org/wiremock/docker/it/extensions/WireMockContainerExtensionsWebhookTest.java
  test/integration-tests/src/test/java/org/wiremock/docker/it/util/HttpResponse.java
  test/integration-tests/src/test/java/org/wiremock/docker/it/util/TestHttpClient.java
  test/integration-tests/src/test/java/org/wiremock/docker/it/util/TestHttpServer.java
  test/integration-tests/src/test/resources/org/wiremock/docker/it/extensions/WireMockContainerExtensionsWebhookTest/webhook-callback-template.json
Labels: chore

#89 Document the integration test suite
  test/integration-tests/README.md
Labels: documentation

#90 #78 - Add support for WireMock CLI options as environment variable
  alpine/docker-entrypoint.sh
  docker-entrypoint.sh
  test/integration-tests/src/test/java/org/wiremock/docker/it/WireMockOptionsTest.java
Labels: enhancement

#92 Fix WIREMOCK_OPTIONS duplicated
  alpine/docker-entrypoint.sh
  docker-entrypoint.sh
Labels: bug

#93 Use the WireMock module for Testcontainers from Maven Central
  test/integration-tests/pom.xml
Labels: chore
