Repository wiremock/wiremock-docker, pull requests merged in 2023-08, with the labels that each got.

#76 Update the 3.x experimental images to WireMock 3.0.0-beta-14
  Dockerfile
  alpine/Dockerfile
Labels: dependencies

#75 Document the experimental 3.x Beta images
  readme.md
Labels: documentation

#74 WireMock 3.x Docker images
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  Dockerfile
  Dockerfile-nightly
  alpine/Dockerfile
  alpine/Dockerfile-nightly
  alpine/docker-entrypoint.sh
  docker-entrypoint.sh
  readme.md
Labels: enhancement, dependencies

#80 Update Dockerfile eclipse-temurin version
  Dockerfile
Labels: dependencies

#79 Update WireMock to 3.0.1 with bugfixes + Update Eclipse Temurin to 11.0.20_8
  .github/workflows/release.yml
  Dockerfile
  Dockerfile-nightly
  alpine/Dockerfile
  alpine/Dockerfile-nightly
Labels: dependencies
